
### Get All Product Types
GET  http://localhost:9000/api/products/neutral-signature-soft-touch-wool-rich-epsom-coat-24f09c
### Delete
GET  http://localhost:9000/api/product-types

### Get Single Product Type
# GET http://localhost:9000/api/product-types/{{PRODUCT_TYPE_ID}}

